support cloudwatch data source in grafana
vito/grafana-boshrelease pull request #16
Opened 2016-09-23 07:39 UTC by m-richo

as discussed in issue #12 

grafana cloudwatch data source is looking for aws credentials in `$HOME/.aws/credentials`.
this PR creates the credentials file in `/var/vcap/jobs/grafana/home/.aws/credentials` containing AWS keys and set $HOME env-var for the grafana-server process launched by the `chpst` command.

I've tested it locally in bosh-lite and works fine.

2016-09-24 15:00 UTC, vito commented on jobs/grafana/templates/credentials
> +[default]
Looks like this template isn't referenced by the spec. It should be put under `home/.aws/...` right?

2016-09-24 15:00 UTC, vito requested changes

2016-09-24 21:58 UTC, m-richo commented on jobs/grafana/templates/credentials
> +[default]
doh.  I'm a dill.  You are right.  
i went to take in your most recent changes before submitting the PR and managed to remove it from the spec file.  I'll update, rebase and send through.

2016-09-24 21:59 UTC, vito approved these changes

2016-09-24 22:00 UTC, vito commented on jobs/grafana/templates/credentials
> +aws_access_key_id = <%= p("grafana.aws.aws_access_key_id") %>
Ah these should also have a default or something; right now this template will blow up rendering if those properties aren't specified.

2016-09-24 22:00 UTC, vito requested changes

2016-09-24 22:02 UTC, m-richo commented on jobs/grafana/templates/credentials
> +aws_access_key_id = <%= p("grafana.aws.aws_access_key_id") %>
any preference on having them as empty strings vs dummy keys?

2016-09-24 22:41 UTC, vito commented on jobs/grafana/templates/credentials
> +aws_access_key_id = <%= p("grafana.aws.aws_access_key_id") %>
Empty string should be fine as long as it parses. Not sure if it does in this format.

2016-09-26 05:07 UTC, m-richo commented on jobs/grafana/templates/credentials
> +aws_access_key_id = <%= p("grafana.aws.aws_access_key_id") %>
tested it with defaults of empty string.  Bosh creates file successfully with
```
$ cat credentials
[default]
aws_access_key_id =
aws_secret_access_key =
region =
```

2016-11-30 05:16 UTC, m-richo commented
G'day,
I've rebased to include the grafana 4.0 updates and it still seems to work fine.  Do you have any further feedback or questions?

Cheers,
Michael

2017-10-02 23:23 UTC, vito approved these changes

2017-10-02 23:23 UTC, vito commented
thanks and sorry for the delay!

2017-10-02 23:23 UTC, merged